logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

server:
  port: 8189
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      default-schema: security_schema
  flyway:
    enabled: true
    cleanOnValidationError: false
    cleanDisabled: false
    locations: classpath:db/migration
    schemas: security_schema
    baselineOnMigrate: true
    baselineVersion: 1
    validateOnMigrate: true
    outOfOrder: false

token:
  signing:
    key: 2d114e9acf363847bacd697a4ca55033d6ad478ee0c130f6de2a7a75b15939e4dd242370a1c132d9e2c184c9e65d9424b4aa828caf55

